---
apiVersion: v1
kind: Secret
metadata:
  name: creds
type: kubernetes.io/basic-auth
stringData:
  username: rebrain 
  password: secret

---
apiVersion: v1
data:
  nginx.conf: |2

    user  nginx;
    worker_processes  4;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6...iY0hWc2JDMWpjbVZrY3pwbmJIQmhkQzEyYm5CTVgybDJOMWQ0WkhwQ01sRlJkVXRGUlE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: registry.rebrainme.com/workshops/middle/kubernetes-local/newplatform_autochecks/nginx:latest
    name: nginx
    env:
    - name: COOL_USER
      valueFrom:
        secretKeyRef:
          name: creds
          key: username
    - name: COOL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: creds
          key: password
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: site-data
      subPath: nginx.conf
  imagePullSecrets:
  - name: regcred
  volumes:
  - name: site-data
    configMap:
      name: nginx-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
